### ISSUE TITLE
Smart Mode keeps fan on during hibernate

### ISSUE THREAD

**Issue by mjiderhamn** [Shuzhengz/TPFanCtrl2#21] opened 2022-03-02 07:11 UTC
**Describe the bug**
If running TPFanCtrl2 in Smart Mode and then putting the computer in hibernation mode, the fan keeps running. This in turn means the battery is drained while hibernating.

**To Reproduce**
Steps to reproduce the behaviour:
* Start TPFanCtrl2 with default settings.
* Switch to Smart Mode
* Make the computer Hibernate

**Expected behaviour**
Fan is turned off during hibernation, as it is without TPFanCtrl2 running.

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H1
 - CPU Intel Core i7-1165G7
 - BIOS version N32ET75W 1.51
 - Software release version 2.1.2
 - Additional hardware information Thinkpad X1 Carbon Gen 9

**Comment by Shuzhengz** [comment] 2022-03-03 04:28
Hmm that's weird. Thanks for bringing it up, I'll definitely look into it

**Comment by Shuzhengz** [comment] 2022-03-03 05:10
The fans turn off for me during hibernate on smart (also on Windows 10 21H1, ThinkPad X1 Extreme). I think it might have something to do with Lenovo's easy resume feature, or just newer Thinkpad models' EC.

I'll try adding power mode change detection and see if it helps.

**Comment by mjiderhamn** [comment] 2022-03-03 08:01
Can I help by supplying any logs?

**Comment by Shuzhengz** [comment] 2022-03-04 07:05
I don't think power changes or window closing actions are implemented yet, so they won't show up on logs. Thanks tho!

**Comment by Shuzhengz** [comment] 2022-03-12 21:58
cool try this

[tpfc.zip](https://github.com/Shuzhengz/TPFanCtrl2/files/8238532/tpfc.zip)

**Comment by mjiderhamn** [comment] 2022-03-14 14:02
> cool try this
> 
> [tpfc.zip](https://github.com/Shuzhengz/TPFanCtrl2/files/8238532/tpfc.zip)

Fans still running while hibernating with this one also.

**Comment by 0xbb** [comment] 2022-03-14 14:19
Maybe unrelated: My X1 Extreme Gen 4 also keeps the fan spinning in standby (sleep) even without tpfc.
I usually turn off the modern standby on newer Thinkpads and this problem goes away: https://www.drwindows.de/xf/attachments/anmerkung-2020-02-21-050059-jpg.214555/ https://www.drwindows.de/xf/attachments/anmerkung-2020-02-21-050017-jpg.214554/

**Comment by Shuzhengz** [comment] 2022-03-16 02:24
@mjiderhamn maybe try this config, I tuned the fan curve so the fan shuts off earlier than usual, and ramps up quicker.
[TPFanControl.zip](https://github.com/Shuzhengz/TPFanCtrl2/files/8258419/TPFanControl.zip)

**Comment by mjiderhamn** [comment] 2022-03-21 08:25
@0xbb , with Sleep State mode Linux set in UEFI, fans turn off in hibernation mode even with TPFC running. In Windows mode, fans stop without TPFC but keep spinning with TPFC.

**Comment by Shuzhengz** [comment] 2022-12-04 07:28
closing issue due to inactivity, and problem is caused by microsoft's inplementation of modern standby (linux sleep mode uses stage 3 sleep so it doesn't do weird stuff)

**Closed by Shuzhengz** 2022-12-04 07:28 UTC
Labels: bug
